services:
  fetch-api:
    build: .
    restart: always
    #network_mode: "host"
    ports:
      - "8010:8010"
    volumes:
      - /fetch:/app/data/
    #env_file:
    #  - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
